name: PR Validation

on:
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Verify
        run: mvn clean verify -Ddependency-check.skip=true -Dspotbugs.skip=true
